version: '2.1'

services:
  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    healthcheck:
      test: ["CMD-SHELL", "psql -h 'localhost' -U 'postgres' -c '\\l'"]
      interval: 30s
      timeout: 30s
      retries: 3

  elixir:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    environment:
      - MIX_ENV
      - DATABASE_URL
    ports:
      - "4000:4000"
    volumes:
      - ..:/app
    working_dir: /app
    depends_on:
      postgres:
        condition: service_healthy
    links:
      - postgres

  scout:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: everydayhero/scout:latest
    environment:
      - DATABASE_URL=postgres://postgres:password@postgres/scout
      - HOST=scout.com
      - PORT=8080
      - REPLACE_OS_VARS=true
      - SECRET_KEY_BASE=SUPER_SECRET_KEY_BASE
      - COOKIE=SUPER_SECRET_COOKIE
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    links:
      - postgres
