version: '2.1'

volumes:
  build:
    driver: local

services:
  postgres:
    image: postgres:9.5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    healthcheck:
      test: ["CMD-SHELL", "psql -h 'localhost' -U 'postgres' -c '\\l'"]
      interval: 30s
      timeout: 30s
      retries: 3

  elixir:
    image: bitwalker/alpine-elixir:1.4.5
    environment:
      - MIX_ENV
      - DATABASE_URL
      - COOKIE
    volumes:
      - ..:/app
      - ../.mix:/root/.mix
      - build:/app/_build
      - ../releases:/app/_build/prod/rel/scout/releases
    working_dir: /app
    depends_on:
      postgres:
        condition: service_healthy
    links:
      - postgres

  scout:
    image: mbuhot/scout
    environment:
      - DATABASE_URL=postgres://postgres:password@postgres/scout
      - HOST=scout.com
    depends_on:
      postgres:
        condition: service_healthy
    links:
      - postgres
    ports:
      - 8080:8080
